### ISSUE TITLE
python package index 등록 

### ISSUE THREAD

**Issue by AhnSeongHyun** [jungkoo/flask-dmango#3]
python package index 에 등록해서 

`pip install flask-dmango`

이런식으로 쓸 수 있도록 하면 편할듯.

**Comment by jungkoo** [comment]
아직 기능이 부족한데 등록해도 되나요?

**Comment by AhnSeongHyun** [comment]
기능은 버전 올리면서 추가하면 될듯. ㅎ
테스트 상의 별 문제 없으면 올려도 될듯 싶네요

**Comment by jungkoo** [comment]
등록했어요
https://pypi.python.org/pypi/Flask-Dmango/0.0.4
- 등록할때 참고했던 글
  https://www.snip2code.com/Snippet/1055012/python-package-index----------
