### ISSUE TITLE
TypeError: 'PyMongo' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by AhnSeongHyun** [jungkoo/flask-dmango#4]
```
@bp.route('/')
def index():
    try:
        db = Dmango.find_mongodb('server1')
        print db, dir(db)
        r1 = db.db['p1'].find()
        print r1.count()
        result = db["p1"].find() #발생위치 
        render_template('index.html', data=result)
    except:
        import traceback
        print traceback.format_exc()
```

```
<flask_pymongo.PyMongo object at 0x7fef7303c790> ['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'config_prefix', 'cx', 'db', 'init_app', 'save_file', 'send_file']
2
Traceback (most recent call last):
  File "/home/ash84/DmangoBanana/views/index.py", line 14, in index
    result = db["p1"].find()
TypeError: 'PyMongo' object has no attribute '__getitem__'
```

**Comment by AhnSeongHyun** [comment]
연결 대상은 mongolab.com 

`dmango.register_mongodb('server1', URI='mongodb://test:test@ds061701.mlab.com:61701/pkast')`

**Comment by jungkoo** [comment]
~~위 문제는 Flask-Dmango 는 쿼리는 필수 조건이라 그렇습니다.~~
~~pymongo 하위 버전이라면 다음과 같이 사용해 보시기 바랍니다.~~
~~#result = db["p1"].find() #발생위치~~ 
~~result = db["p1"].find({}) #발생위치~~
~~(수정: 16/3/27. 위 내용은 잘못된 내용입니다. Pymongo객체라 리턴되므로 잘못된 이야기입니다)~~ 

현재 Flask-Dmango 의 경우 mongodb 3.0을 공식 지원하고 있지 않습니다.
그래서 mlab (mongolab)의 경우 다음과 같은 이유로 사용이 안될수 있습니다.
0.0.5 버전에서 다음과 같이 몽고디비 3.0을 지원할수 있도록 대응하겠습니다. (mlab)
- mongodb 3.0 버전이 올라가면서 pymongo 상위 버전이 필요하고
- Pymongo 버전이 올라가면서 find 함수에서 필드 제한하는 fields 옵션이 projection 으로 명칭 변경
- find() 에서 match 생략 가능하도록 지원

### 참고링크

https://docs.mongodb.org/ecosystem/drivers/driver-compatibility-reference/#python-driver-compatibility

https://api.mongodb.org/python/current/api/pymongo/collection.html

**Comment by jungkoo** [comment]
https://pypi.python.org/pypi/Flask-Dmango 버전업 했습니다.

그리고,  `Dmango.find_mongodb('server1')` 형태로 가져온건 flask-pymongo 에서의 오브젝트입니다.
이때 cx 하위로 call  하면 가져올수 있습니다. 

``` py
# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
from flask import Flask, Blueprint, render_template
from flask_dmango import Dmango

app = Flask(__name__)
dmango = Dmango(app)
dmango.register_mongodb('server1', URI='mongodb://test:test@ds061701.mlab.com:61701/pkast')

bp = Blueprint('name1', __name__)

@bp.route('/')
def index():
    try:
        connection = Dmango.find_mongodb('server1')
        database = connection.cx["pkast"]
        collection = database['p1']
        r1 = collection.find()
        print r1
        print r1.count()
        result = collection.find() #발생위치
        return render_template('index.html', data=result)
    except:
        import traceback
        print traceback.format_exc()

app.register_blueprint(bp)

if __name__ == '__main__':
    app.run(debug=True)
```

참고로 collection 접근은 이렇게 하는게 편합니다.
Dmango.find_collection 메소드를 이용해 가져오는 방법인데, 
랩핑된  `DmangoEngine` 클래스를 리턴하기 때문에, 
리턴된 값에서 collection을 다시 호출하는겁니다 (프로퍼티로 해둠)

``` py
dmango_engine = Dmango.find_collection('server1', db_name='pkast', collection_name='p1')
collection = dmango_engine.collection  # flask-pymongo 의 collection 접근
...
collection.find()
```

그리고 드망고의 장점인 restapi 기본 제공도 아래와 같이 됩니다.
- api
  http://127.0.0.1:5000/dmango/server1.pkast.p1/find
- admin list (아직 미개발)
  http://127.0.0.1:5000/dmango_admin/server1.pkast.p1/list

**Comment by jungkoo** [comment]
Dmango 에서 mongodb 접속 정보가 싱글턴 형태로 관리되는데요.
최초에는 restapi로만 활용해서 쓰는걸 최우선으로 해서 개발하다보니 외부에서 해당 정보를 쓸거라고 별로 생각을 안했었는데 이런일이 있군요. flask의 블루프린트를 활용하여 사용할때 외부사람이 사용할걸 고려해 발전해야겠네요.

참고로  이런게 존재합니다.

app.register_blueprint(bp) 로 등록하지 않고
dmango.register_blueprint(bp) 로 등록하면 
request 객체에 dmango 관련한 파라미터에 대한 파싱결과를 볼수 있습니다. 

성능을 고려해 lazy 파싱을 하므로, match 나 sort 같이 `request.dmango.xxx` 형태의 프로퍼티를 호출해야 합니다.

참고할건 AbstractRequestDmango 의 프로퍼티 부분을 참고하면 됩니다.
https://github.com/jungkoo/flask-dmango/blob/master/flask_dmango/request_helpers.py#L10

``` py
bp = Blueprint('name1', __name__)

# ?title=테스트&age:int=5&_sort=title
@bp.route('/')
def index():
    print "dmango>>", request.dmango.match  #==> {title: "테스트", age: 5}
    print "dmango>>", request.dmango.sort      #==> [(u'title', 1)]
...

# app.register_blueprint(bp)
dmango.register_blueprint(bp)  # request 에 damngo 패턴 uri를 파싱한걸 알수 있음.
```
